# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Inseo Jang
title: Computer Graphics Researcher
email: isjang0807@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  loveyourdaddy

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  Great Day! 
  I study and research on Computer Graphics. 
  Currently, I am Ph.D student at VML KAIST in South Korea, advised by Prof. Junyong Noh. My research area is motion retargeting in character animation. Especially, I focus on retargeting interaction motions between multiple characters of various shape that animator can use!
  During my master degree, I was in GML advised by Prof. Hyeong-Seok Ko. I studied cloth simulation and conducted research on improving the simulation speed.  
  I am grateful for the opportunity to learn new things and look forward to experiencing new challenges.
Research Topic: Character animation, Motion retargeting, Cloth simulation
  # Good Day! my name's Inseo and I'm Ph.D student at GSCT KAIST advised by Prof.Junyoung Noh. My research area is Computer graphics, especially character's motion retargeting using deep-learning. 
  # As well as character animation, I studied physic-based cloth simulation for fast and stable result at SNU advised by Prof Hyeungseok Ko. 
  # I am most skilled in: <mark>Character Animation</mark>

content:
  - title: Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left # middle
        title: Geometry-Aware Retargeting for Two Skinned Character Interaction 
        sub_title: Inseo Jang, Soojin Choi, Seokhyeon Hong, Chaelin Kim, Junyoung Noh (In submisson)
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
        description: | 
        
      - layout: top-left # middle
        title: Pattern Mirroring Algorithm for Fast Simulation 
        sub_title: Inseo Jang, Sangbin Lee, Hyeungseok Ko (KCGS 2018 Proceeding)
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
        description: | 
        Research on Accelerating Cloth Simulation Speed for Symmetrical Motion
# 좌우대칭으로 움직이는 캐릭터의 모션에 대해서 cloth 시뮬레이션 속도를 가속화하기 위한 연구 
# I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
