# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Inseo Jang
title: Computer Graphics Researcher
email: isjang0807@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  loveyourdaddy

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  Great Day! 
  I study and research on Computer Graphics. 

  Currently, I am Ph.D student at VML KAIST in South Korea, advised by Prof. Junyong Noh. My research area is motion retargeting in character animation. Especially, I focus on retargeting interaction motions between multiple characters of various shape that animator can use!
  During my master degree, I was in GML advised by Prof. Hyeong-Seok Ko. I studied cloth simulation and conducted research on improving the simulation speed.  
  
  I am grateful for the opportunity to learn new things and look forward to experiencing new challenges.
Research Topic: Character animation, Motion retargeting, Cloth simulation
  # Good Day! my name's Inseo and I'm Ph.D student at GSCT KAIST advised by Prof.Junyoung Noh. My research area is Computer graphics, especially character's motion retargeting using deep-learning. 
  # As well as character animation, I studied physic-based cloth simulation for fast and stable result at SNU advised by Prof Hyeungseok Ko. 
  # I am most skilled in: <mark>Character Animation</mark>

content:
  - title: Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Geometry-Aware Retargeting for Two Skinned Character Interaction 
        sub_title: Inseo Jang, Soojin Choi, Seokhyeon Hong, Chaelin Kim, Junyoung Noh (In submisson) Images ![alt text](/images/landscape-trees.jpg "Trees")
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            # url: github.com/sproogen/modern-resume-theme
        description: | 
        
      - layout: top-middle
        title: Pattern Mirroring Algorithm for Fast Simulation 
        sub_title: Inseo Jang, Sangbin Lee, Hyeungseok Ko (KCGS 2018 Proceeding)
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://drive.google.com/file/d/11vVcL1xIQH1uR2bKVoa03Memly8Evwqs/view?usp=drive_link
        description: Research on Accelerating Cloth Simulation Speed for Symmetrical Motion # | 


# Footer
footer_show_references: false # true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
